# Generated by Django 5.2.7 on 2025-10-12 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=200)),
                ('file_path', models.FileField(upload_to='orders/%Y/%m/%d/')),
                ('pages_selected', models.CharField(help_text='e.g., 1-5, 10, 15-20', max_length=100)),
                ('color_or_black', models.BooleanField(default=False, help_text='False=Black & White, True=Color')),
                ('landscape_or_portrait', models.BooleanField(default=False, help_text='False=Portrait, True=Landscape')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('shop', 'Shop')], db_index=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', 'role'], name='users_usernam_adcd2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(db_index=True, max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('gst_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'shop'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to='print.user')),
            ],
            options={
                'verbose_name': 'Shop Profile',
                'verbose_name_plural': 'Shop Profiles',
                'db_table': 'shop_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='print.user')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Card', 'Card'), ('Cash', 'Cash'), ('NetBanking', 'Net Banking')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='print.order')),
                ('shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to='print.shopprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='print.userprofile')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='print.userprofile'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='generated', max_length=20)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='print.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='print.payment')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['status', '-invoice_date'], name='invoices_status_da87ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='print.order')),
                ('shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='print.shopprofile')),
            ],
            options={
                'verbose_name': 'Shop Order',
                'verbose_name_plural': 'Shop Orders',
                'db_table': 'shop_orders',
                'indexes': [models.Index(fields=['shop_profile', 'status', '-created_at'], name='shop_orders_shop_pr_6052f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'shop_profile'), name='unique_shop_order')],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_share', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('shop_share', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('commission_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('admin_paid', 'Paid to Admin'), ('shop_paid', 'Paid to Shop'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='print.payment')),
                ('shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='print.shopprofile')),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='commissions_status_d304e2_idx'), models.Index(fields=['shop_profile', 'status'], name='commissions_shop_pr_bcb545_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shopprofile',
            index=models.Index(fields=['shop_name', 'is_active'], name='shop_profil_shop_na_2256cd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status', '-created_at'], name='payments_payment_71f24b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['shop_profile', 'payment_status'], name='payments_shop_pr_256c82_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_profile', '-created_at'], name='orders_user_pr_d4b13f_idx'),
        ),
    ]
