# Generated by Django 5.2.7 on 2025-10-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('shop', 'Shop'), ('shop', 'Admin')], db_index=True, max_length=10),
        ),
    ]
