# Generated by Django 5.2.7 on 2025-10-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0005_alter_shopprofile_user_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'shop'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to='print.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('shop', 'Shop'), ('admin', 'Admin')], db_index=True, max_length=10),
        ),
    ]
