# Generated by Django 5.2.7 on 2025-10-31 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0006_alter_shopprofile_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_shop',
            field=models.ForeignKey(blank=True, help_text='Shop chosen by user after seeing responses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to='print.shopprofile'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
