# Generated by Django 5.2.7 on 2026-02-17 19:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0008_productorder_delivery_store_productorder_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'order_status_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deliveryevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='delivered_at',
            new_name='actual_delivery_time',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='eta',
            new_name='estimated_delivery_time',
        ),
        migrations.RenameIndex(
            model_name='deliveryevent',
            new_name='delivery_ev_deliver_246272_idx',
            old_name='print_deliv_deliver_a288cb_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryevent',
            new_name='delivery_ev_status_80364f_idx',
            old_name='print_deliv_status_d5fc61_idx',
        ),
        migrations.RenameIndex(
            model_name='productorderitem',
            new_name='product_ord_order_i_cef5d8_idx',
            old_name='print_produ_order_i_78774a_idx',
        ),
        migrations.AddField(
            model_name='delivery',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_person_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='delivery',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productorder',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='customer_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='productorder',
            name='customer_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productorder',
            name='estimated_ready_time',
            field=models.DateTimeField(blank=True, help_text="Vendor's estimate for when order will be ready", null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order_number',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, help_text='e.g., ORD-20260218-001234', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productorder',
            name='vendor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='product_sku_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='tracking_code',
            field=models.CharField(db_index=True, help_text='e.g., TRK-20260218-001234', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deliveryevent',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned to Delivery Person'), ('picked_up', 'Picked up from Store'), ('in_transit', 'In Transit'), ('at_location', 'At Delivery Location'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=30),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['assigned_to', 'is_completed'], name='deliveries_assigne_9af36c_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tracking_code'], name='deliveries_trackin_b1b1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['user_profile', '-created_at'], name='product_ord_user_pr_73f0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['store', 'status', '-created_at'], name='product_ord_store_i_3e38d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['order_number'], name='product_ord_order_n_db7e93_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['status', '-created_at'], name='product_ord_status_53653c_idx'),
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='deliveries',
        ),
        migrations.AlterModelTable(
            name='deliveryevent',
            table='delivery_events',
        ),
        migrations.AlterModelTable(
            name='productorder',
            table='product_orders',
        ),
        migrations.AlterModelTable(
            name='productorderitem',
            table='product_order_items',
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made the change (customer/vendor/admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='print.productorder'),
        ),
        migrations.AddIndex(
            model_name='orderstatuslog',
            index=models.Index(fields=['order', '-changed_at'], name='order_statu_order_i_6a1e7e_idx'),
        ),
    ]
