# Generated by Django 5.2.7 on 2026-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0009_orderstatuslog_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
