# Generated by Django 5.2.7 on 2026-03-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vendor's quoted price; triggers financial recalculation", max_digits=10, null=True),
        ),
    ]
