# Generated by Django 5.2.7 on 2026-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0013_productorder_quoted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='original_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of total before vendor quoted price overwrite', max_digits=10, null=True),
        ),
    ]
