# Generated by Django 5.2.7 on 2026-03-10 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0014_productorder_original_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='original_total',
        ),
        migrations.AddField(
            model_name='productorder',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='The ProductOrder this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='print.productorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='product_pay_order_i_9ec959_idx'), models.Index(fields=['razorpay_order_id'], name='product_pay_razorpa_9637b9_idx'), models.Index(fields=['status'], name='product_pay_status_a7be01_idx')],
            },
        ),
    ]
