# Generated by Django 5.2.7 on 2026-03-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0015_remove_productorder_original_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpayment',
            name='amount_paise',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='print.productorder'),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
    ]
